disabled_rules:
  - trailing_whitespace
  - opening_brace

excluded:
  - Pods
  - SwiftLint/Common/3rdPartyLib
  - "{{cookiecutter.app_name}}/Resources/Generated/R.generated.swift"
  - "Modules/Sources/Authentication/R.generated.swift"
  - "{{cookiecutter.app_name}}/Modules/Sources/NetworkPlatform/Common/HTTPStatusCode.swift"

force_cast: warning

reporter: "xcode"
